### ISSUE TITLE
How do I setup RedisURL is the config.json

### ISSUE THREAD

**Issue by aidanw-dev** [DottoXD/statusmonitor-server#5]

**Comment by DottoXD** [comment]
Hey, you should put a valid redis connection url like this one:
redis://username:password@ip:port

**Comment by aidanw-dev** [comment]
Yeah but where do I get all of that stuff, where do I get those stuff, here? https://redis.com

**Comment by DottoXD** [comment]
Yes, you can get a free 32MB redis database there

**Comment by aidanw-dev** [comment]
And I get Redis Stack?

**Comment by DottoXD** [comment]
I don’t remember how their free 32MB plan was called, you should find it on that website

**Comment by aidanw-dev** [comment]
I got the username and password and port but not the ip. Do you know where I find the ip?

**Comment by DottoXD** [comment]
They are probably giving you a subdomain instead of an IP, it works too

**Comment by aidanw-dev** [comment]
Its not working I have this redis://skyhost:pass@redis-18399.c74.us-east-1-4.ec2.cloud.redislabs.com:18399

@DottoXD

**Comment by DottoXD** [comment]
Uh i don't know, it should be working fine.

**Comment by aidanw-dev** [comment]
I got a different error

 return new ReplyError(string)
           ^

ReplyError: NOAUTH Authentication required
    at parseError (C:\Users\aidan\OneDrive\Desktop\status web 2\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\Users\aidan\OneDrive\Desktop\status web 2\node_modules\redis-parser\lib\parser.js:302:14) {
  command: {
    name: 'evalsha',
    args: [
      '8f55ae4a3be429c6d38c5d5db3e80edf89197b64',
      '6',
      'bull:StatusMonitorQueue:wait',
      'bull:StatusMonitorQueue:paused',
      'bull:StatusMonitorQueue:meta-paused',
      'bull:StatusMonitorQueue:id',
      'bull:StatusMonitorQueue:delayed',
      'bull:StatusMonitorQueue:priority',
      'bull:StatusMonitorQueue:',
      '',
      '__default__',
      '{"data":"StatusMonitorQueue"}',
      '{"delay":5000,"attempts":1,"timestamp":1651182515750}',
      '1651182515750',
      '5000',
      '1651182520750',
      '0',
      'LPUSH',
      'e29d9bfb-35e2-4a46-8c76-790072761274'
    ]
  }
}

**Comment by DottoXD** [comment]
Uh i don't know what could be causing this
